### ISSUE TITLE
[Proposal] ALiAS Summer of Code

### ISSUE THREAD

**Issue by NebulaTris** [asetalias/events#74]
### Type

Event

### About

- To work in the following Projects (below -mentioned) under ALiAS Summer of Code 
- Possible Contribution Period for 2 weeks.

Project list:
-Amibots (Whatsapp, Telegram, Discord)
-go amizone [important]
-Alias website
-AmiVerse (A WIP amizone app for iOS and Android written in react native)
-Amigrant ( Tentative)
-Volunteers can add on their projects. 

### Pre-requisites

- laptop
- internet connection
- account on github

### Duration

1.5 months

### To do

Selection phase:
- [x] Select mentors ~ 1 week (25th june)
- [x] Finalize projects ~ 1 week (25th june )
[can include AliAS and Intermediate NTCC projects ]
- [x] Finalize potential sponsors ~ 1 week (25th)
[Just have a list of potential sponsors to reach  out to}
- [x] Finalize contribution period rules ~ 1 week (25th)
- [x] Finalize post project prep phase ~ 1.5 weeks

Project prep phase:
- [x] scaffold projects: ~1 month (25th july)
[AmiVerse (app) , Amigrant (notes site)]
- [x] finalize github contribution period issues ~ 2 weeks (11th July)
- [x] finalize contributing period issues ~ 2 weeks ( 11th July)
- [x] finalize major issues for contributing period ~ 3 weeks (18th July)
- [x] finalize sponsors ~ 1month(25th July)
- [x] finalize a timeline for mentees ~ 2 weeks

Other Important Tasks :
- [x] decide on contributing timeline
- [x] decide on what winners get
- [ ] get certificate approval from Shilpi ma'am
- [x] secure sponsorships
- [x] Need to create form for :
  1) Mentees List
  2) Mentors List
  3) Adding Projects

### Mentors

Potential Mentors List:

Priyanshu
Manik
Achintya
Tushar
Advik 
Ashwin
Vinayak
Sagar
Shivam
Venkatesh

**Comment by jailbreakerVC** [comment]
Old timeline is now deprecated, refer to the new timeline below

6th - 23rd August: Registration Period 
24th August: Habituation 
28th -30th August: Shortlisting
31st Aug to 25th Sept: Contribution period
01-04 October: Evaluation (if reqd)
05th October: Conclusion of the event

**Comment by jailbreakerVC** [comment]
The exact timeline will be pushed to the ASoC website by the coming week.

**Comment by jailbreakerVC** [comment]
Ho gaya balle balle
